import fs from 'node:fs';
import path from 'node:path';

/**
 * Apache configuration that we drop into the WordPress container's
 * `conf-enabled/` directory so the bundled Apache plays nicely with kiqr's
 * reverse-proxy / tunnel setup.
 *
 * Two things this fixes that no amount of PHP-side tweaking can:
 *
 * 1. `SetEnvIfNoCase X-Forwarded-Proto https HTTPS=on` -- exposes the HTTPS
 *    flag to PHP for non-WordPress entry points (mu-plugin's
 *    WORDPRESS_CONFIG_EXTRA already sets `$_SERVER['HTTPS']`, but only inside
 *    wp-config.php execution; this covers anything else served by Apache).
 *
 * 2. `<Directory>` rewrite that pre-empts mod_dir's DirectorySlash 301.
 *    When a tunneled visitor hits `/wp-admin` (no trailing slash), mod_dir
 *    would emit `Location: http://<rewritten-Host>/wp-admin/` -- the
 *    Apache-internal http hop + cloudflared's `--http-host-header` rewrite,
 *    NOT the public tunnel URL. The browser follows, the local URL has no
 *    HTTPS service, and the user gets ERR_CONNECTION_REFUSED.
 *
 *    Using `RewriteOptions InheritDownBefore`, our rule runs BEFORE the
 *    WordPress `.htaccess` (whose `!-d` condition lets the request fall
 *    through to mod_dir). The rule fires only when X-Forwarded-Proto is
 *    https AND X-Forwarded-Host is set -- so plain local browsing keeps
 *    Apache's default behavior (and port preservation).
 */
const APACHE_CONF_CONTENT = `# Generated by @kiqr/cli -- do not edit by hand.
# Trust X-Forwarded-Proto from the kiqr agent's Traefik front-end so PHP
# sees HTTPS=on for non-WP entry points (e.g. static PHP scripts).
SetEnvIfNoCase X-Forwarded-Proto https HTTPS=on

<Directory "/var/www/html">
    RewriteEngine On
    # Pull this rule into .htaccess in this directory BEFORE the WordPress
    # rules already there. Without InheritDownBefore our rule never runs --
    # the WP .htaccess takes over and mod_dir gets to do its DirectorySlash.
    RewriteOptions InheritDownBefore

    # Tunneled directory-without-trailing-slash: redirect ourselves with
    # the original https scheme + X-Forwarded-Host instead of Apache's
    # local-hop scheme + cloudflared-rewritten Host.
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteCond %{REQUEST_URI} !/$
    RewriteCond %{HTTP:X-Forwarded-Proto} =https
    RewriteCond %{HTTP:X-Forwarded-Host} ^([^,]+)$
    RewriteRule ^(.+)$ https://%1/$1/ [R=301,L,NE]
</Directory>
`;

/** Write the Apache conf into the project's runtime dir and return its path. */
export function writeApacheConf(runtimeDir: string): string {
  const filePath = path.join(runtimeDir, 'kiqr-apache.conf');
  fs.mkdirSync(runtimeDir, {recursive: true});
  fs.writeFileSync(filePath, APACHE_CONF_CONTENT, 'utf-8');
  return filePath;
}
