/**
 * Pure, deterministic generator for WordPress demo content.
 *
 * The output is a WXR (WordPress eXtended RSS) 1.2 document that can be fed
 * straight into `wp import`. Everything here is intentionally free of any
 * time- or randomness-based APIs: every date is a fixed literal so that the
 * exact same bytes are produced on every run (which keeps it diff-friendly and
 * unit-testable).
 */

export const SEED_PRESETS = ['blog', 'portfolio', 'woocommerce'] as const;

export type SeedPreset = (typeof SEED_PRESETS)[number];

/** A single content node that becomes one `<item>` in the WXR feed. */
type SeedItem = {
  /** Sequential id; also used for the post id and menu order. */
  id: number;
  title: string;
  /** URL slug, used for `<wp:post_name>` and the guid. */
  slug: string;
  /** WordPress post type: post, page, product, etc. */
  postType: string;
  /** Full block-editor markup for `<content:encoded>`. */
  content: string;
  /** Short excerpt for `<excerpt:encoded>`. */
  excerpt: string;
  /** Literal date string, e.g. '2024-01-15T10:00:00' (no timezone, no `Z`). */
  date: string;
};

const SITE_TITLE = 'Kiqr Demo Site';
const SITE_LINK = 'https://example.test';
const SITE_DESCRIPTION = 'Demo content generated by the Kiqr CLI';
const AUTHOR_LOGIN = 'kiqr';
const AUTHOR_NAME = 'Kiqr Demo';
const AUTHOR_EMAIL = 'demo@example.test';

/**
 * Build a single block-editor paragraph. Wrapping the markup in the core block
 * comments keeps the imported content editable as native Gutenberg blocks
 * rather than a "Classic" blob.
 */
function paragraph(text: string): string {
  return `<!-- wp:paragraph -->\n<p>${escapeHtml(text)}</p>\n<!-- /wp:paragraph -->`;
}

function heading(text: string): string {
  return `<!-- wp:heading -->\n<h2 class="wp-block-heading">${escapeHtml(text)}</h2>\n<!-- /wp:heading -->`;
}

function list(items: string[]): string {
  const inner = items
    .map(
      (item) =>
        `<!-- wp:list-item -->\n<li>${escapeHtml(item)}</li>\n<!-- /wp:list-item -->`,
    )
    .join('\n');
  return `<!-- wp:list -->\n<ul class="wp-block-list">\n${inner}\n</ul>\n<!-- /wp:list -->`;
}

/** Compose several block fragments into one `<content:encoded>` payload. */
function blocks(...fragments: string[]): string {
  return fragments.join('\n\n');
}

/** Escape the five XML-significant characters for use in element text. */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/** Wrap a value in a CDATA section, neutralising any nested terminators. */
function cdata(value: string): string {
  return `<![CDATA[${value.replace(/]]>/g, ']]]]><![CDATA[>')}]]>`;
}

/**
 * WordPress stores two timestamps per post: site-local and GMT. The demo
 * content uses UTC, so both columns share the same literal value (just
 * reformatted from ISO `T` notation to the space-separated SQL form).
 */
function sqlDate(date: string): string {
  return date.replace('T', ' ');
}

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const;
const MONTHS = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
] as const;

/** Convert an ISO-ish literal to the RFC-822 `<pubDate>` WordPress emits. */
function pubDate(date: string): string {
  const datePart = date.split('T')[0] ?? '';
  const timePart = date.split('T')[1] ?? '00:00:00';
  const parts = datePart.split('-');
  const year = Number.parseInt(parts[0] ?? '0', 10);
  const month = Number.parseInt(parts[1] ?? '1', 10);
  const day = Number.parseInt(parts[2] ?? '1', 10);

  // Zeller-style weekday calculation; deterministic and dependency-free.
  const m = month < 3 ? month + 12 : month;
  const y = month < 3 ? year - 1 : year;
  const k = y % 100;
  const j = Math.floor(y / 100);
  const h =
    (day +
      Math.floor((13 * (m + 1)) / 5) +
      k +
      Math.floor(k / 4) +
      Math.floor(j / 4) +
      5 * j) %
    7;
  const weekday = WEEKDAYS[(h + 6) % 7];
  const monthName = MONTHS[month - 1];
  return `${weekday}, ${String(day).padStart(2, '0')} ${monthName} ${year} ${timePart} +0000`;
}

function renderItem(item: SeedItem): string {
  const link = `${SITE_LINK}/?p=${item.id}`;
  return [
    '\t\t<item>',
    `\t\t\t<title>${escapeHtml(item.title)}</title>`,
    `\t\t\t<link>${link}</link>`,
    `\t\t\t<pubDate>${pubDate(item.date)}</pubDate>`,
    `\t\t\t<dc:creator>${cdata(AUTHOR_LOGIN)}</dc:creator>`,
    `\t\t\t<guid isPermaLink="false">${link}</guid>`,
    '\t\t\t<description></description>',
    `\t\t\t<content:encoded>${cdata(item.content)}</content:encoded>`,
    `\t\t\t<excerpt:encoded>${cdata(item.excerpt)}</excerpt:encoded>`,
    `\t\t\t<wp:post_id>${item.id}</wp:post_id>`,
    `\t\t\t<wp:post_date>${cdata(sqlDate(item.date))}</wp:post_date>`,
    `\t\t\t<wp:post_date_gmt>${cdata(sqlDate(item.date))}</wp:post_date_gmt>`,
    `\t\t\t<wp:comment_status>${cdata('open')}</wp:comment_status>`,
    `\t\t\t<wp:ping_status>${cdata('open')}</wp:ping_status>`,
    `\t\t\t<wp:post_name>${cdata(item.slug)}</wp:post_name>`,
    `\t\t\t<wp:status>${cdata('publish')}</wp:status>`,
    `\t\t\t<wp:post_parent>0</wp:post_parent>`,
    `\t\t\t<wp:menu_order>${item.id}</wp:menu_order>`,
    `\t\t\t<wp:post_type>${cdata(item.postType)}</wp:post_type>`,
    `\t\t\t<wp:post_password>${cdata('')}</wp:post_password>`,
    `\t\t\t<wp:is_sticky>0</wp:is_sticky>`,
    '\t\t</item>',
  ].join('\n');
}

/** Items for the `blog` preset: a handful of posts plus an About page. */
function blogItems(): SeedItem[] {
  const posts: SeedItem[] = [
    {
      id: 10,
      title: 'Welcome to the Kiqr Demo',
      slug: 'welcome-to-the-kiqr-demo',
      postType: 'post',
      date: '2024-01-15T10:00:00',
      excerpt: 'A quick tour of what this demo content is for.',
      content: blocks(
        paragraph(
          'This post and the rest of this demo content were generated by the Kiqr CLI so you can preview your theme against a realistic, populated site instead of an empty install.',
        ),
        heading('Why demo content?'),
        paragraph(
          'A fresh WordPress install has no posts, pages, or media, which makes it hard to judge typography, spacing, and archive layouts. Seeded content fixes that in seconds.',
        ),
      ),
    },
    {
      id: 11,
      title: 'Designing Readable Typography',
      slug: 'designing-readable-typography',
      postType: 'post',
      date: '2024-02-03T09:30:00',
      excerpt: 'Notes on line length, rhythm, and contrast for body text.',
      content: blocks(
        paragraph(
          'Good body typography is mostly about measure and rhythm. Aim for 60 to 75 characters per line and a comfortable line height around 1.6.',
        ),
        list([
          'Keep your measure between 60 and 75 characters.',
          'Use a modular scale for headings.',
          'Test contrast against your lightest background.',
        ]),
      ),
    },
    {
      id: 12,
      title: 'A Field Guide to Whitespace',
      slug: 'a-field-guide-to-whitespace',
      postType: 'post',
      date: '2024-03-12T14:15:00',
      excerpt: 'Whitespace is a feature, not wasted space.',
      content: blocks(
        paragraph(
          'Whitespace gives content room to breathe and guides the eye through a page. Treat it as a deliberate design tool rather than leftover margin.',
        ),
        paragraph(
          'When a layout feels cramped, the fix is rarely a smaller font. More often it is more space between elements.',
        ),
      ),
    },
    {
      id: 13,
      title: 'Shipping a Theme with Confidence',
      slug: 'shipping-a-theme-with-confidence',
      postType: 'post',
      date: '2024-04-08T08:00:00',
      excerpt: 'A checklist for the day you hand a theme to a client.',
      content: blocks(
        paragraph(
          'Before you ship, walk through every template against real content. Long titles, missing images, and empty archives are where themes usually break.',
        ),
        heading('Pre-flight checklist'),
        list([
          'Single post and page templates.',
          'Category, tag, and author archives.',
          'Search results and the 404 page.',
        ]),
      ),
    },
    {
      id: 14,
      title: 'Color and Contrast Basics',
      slug: 'color-and-contrast-basics',
      postType: 'post',
      date: '2024-05-20T11:45:00',
      excerpt: 'Accessible color is non-negotiable.',
      content: blocks(
        paragraph(
          'Aim for a contrast ratio of at least 4.5 to 1 for body text. Tools in the browser dev tools can flag failing combinations instantly.',
        ),
        paragraph(
          'Never rely on color alone to convey meaning; pair it with text, icons, or underlines so the information survives for every reader.',
        ),
      ),
    },
  ];

  const aboutPage: SeedItem = {
    id: 20,
    title: 'About',
    slug: 'about',
    postType: 'page',
    date: '2024-01-10T08:00:00',
    excerpt: 'About this demo site.',
    content: blocks(
      heading('About this site'),
      paragraph(
        'This is a demo About page. It exists so you can see how your theme renders a long-form static page, complete with headings and paragraphs.',
      ),
      paragraph(
        'Replace this content with your own story once you are happy with the look and feel.',
      ),
    ),
  };

  return [...posts, aboutPage];
}

/** Items for the `portfolio` preset: an intro page plus project pages. */
function portfolioItems(): SeedItem[] {
  const intro: SeedItem = {
    id: 30,
    title: 'Selected Work',
    slug: 'selected-work',
    postType: 'page',
    date: '2024-01-05T09:00:00',
    excerpt: 'An introduction to the portfolio.',
    content: blocks(
      heading('Selected work'),
      paragraph(
        'A small collection of recent projects, generated as demo content so you can preview portfolio and project templates with real-feeling entries.',
      ),
    ),
  };

  const projects: Array<{title: string; slug: string; summary: string; role: string}> = [
    {
      title: 'Northwind Coffee Rebrand',
      slug: 'northwind-coffee-rebrand',
      summary:
        'A full visual identity for a specialty coffee roaster, from logo to packaging and a refreshed storefront.',
      role: 'Brand identity and web design',
    },
    {
      title: 'Harbor Analytics Dashboard',
      slug: 'harbor-analytics-dashboard',
      summary:
        'A data-heavy dashboard that turns shipping logistics into clear, glanceable charts for operations teams.',
      role: 'Product design and front-end',
    },
    {
      title: 'Meadow Botanicals Storefront',
      slug: 'meadow-botanicals-storefront',
      summary:
        'An online shop for a small-batch skincare brand, with a calm palette and a focus on ingredient storytelling.',
      role: 'E-commerce design and build',
    },
    {
      title: 'Atlas Travel Journal',
      slug: 'atlas-travel-journal',
      summary:
        'An editorial travel publication with immersive photo galleries and a typographic system built for long reads.',
      role: 'Editorial design and theming',
    },
  ];

  const projectItems: SeedItem[] = projects.map((project, index) => ({
    id: 40 + index,
    title: project.title,
    slug: project.slug,
    postType: 'page',
    date: `2024-0${index + 2}-15T10:00:00`,
    excerpt: project.summary,
    content: blocks(
      `<!-- wp:cover {"dimRatio":40} -->\n<div class="wp-block-cover"><span aria-hidden="true" class="wp-block-cover__background has-background-dim"></span><div class="wp-block-cover__inner-container">\n<!-- wp:heading {"level":1} -->\n<h1 class="wp-block-heading">${escapeHtml(project.title)}</h1>\n<!-- /wp:heading -->\n</div></div>\n<!-- /wp:cover -->`,
      `<!-- wp:columns -->\n<div class="wp-block-columns">\n<!-- wp:column -->\n<div class="wp-block-column">${paragraph(project.summary)}</div>\n<!-- /wp:column -->\n<!-- wp:column -->\n<div class="wp-block-column">${paragraph(`Role: ${project.role}`)}</div>\n<!-- /wp:column -->\n</div>\n<!-- /wp:columns -->`,
      heading('Outcome'),
      paragraph(
        'This is placeholder project copy. Swap it for a case study describing the problem, your approach, and the result.',
      ),
    ),
  }));

  return [intro, ...projectItems];
}

/** Items for the `woocommerce` preset: a set of demo products. */
function woocommerceItems(): SeedItem[] {
  const products: Array<{
    title: string;
    slug: string;
    price: string;
    blurb: string;
  }> = [
    {
      title: 'Stoneware Pour-Over Set',
      slug: 'stoneware-pour-over-set',
      price: '48.00',
      blurb:
        'A hand-glazed ceramic dripper and matching carafe for a slow, deliberate morning brew.',
    },
    {
      title: 'Merino Travel Blanket',
      slug: 'merino-travel-blanket',
      price: '120.00',
      blurb:
        'Lightweight, breathable merino wool that packs down small and keeps its shape.',
    },
    {
      title: 'Brass Desk Lamp',
      slug: 'brass-desk-lamp',
      price: '95.00',
      blurb: 'An adjustable task lamp with a warm dimmable bulb and a solid brass arm.',
    },
    {
      title: 'Recycled Canvas Tote',
      slug: 'recycled-canvas-tote',
      price: '32.00',
      blurb:
        'A roomy everyday tote sewn from recycled canvas with reinforced shoulder straps.',
    },
    {
      title: 'Cold Brew Concentrate',
      slug: 'cold-brew-concentrate',
      price: '18.50',
      blurb:
        'Small-batch concentrate steeped for eighteen hours; just add water or milk to taste.',
    },
    {
      title: 'Linen Apron',
      slug: 'linen-apron',
      price: '54.00',
      blurb: 'A heavyweight linen apron with adjustable straps and a deep front pocket.',
    },
  ];

  return products.map((product, index) => ({
    id: 50 + index,
    title: product.title,
    slug: product.slug,
    postType: 'product',
    date: `2024-06-${String(index + 1).padStart(2, '0')}T10:00:00`,
    excerpt: product.blurb,
    content: blocks(
      paragraph(product.blurb),
      heading('Details'),
      list([
        `Price: $${product.price}`,
        'Ships within 2 to 3 business days.',
        'Free returns within 30 days.',
      ]),
      paragraph(
        'This is demo product copy. Connect WooCommerce to manage real pricing, inventory, and checkout.',
      ),
    ),
  }));
}

const PRESET_ITEMS: Record<SeedPreset, () => SeedItem[]> = {
  blog: blogItems,
  portfolio: portfolioItems,
  woocommerce: woocommerceItems,
};

/**
 * Generate a complete, valid WXR 1.2 document for the given preset.
 *
 * Pure and deterministic: calling it twice with the same preset returns
 * byte-for-byte identical output.
 */
export function generateSeedWxr(preset: SeedPreset): string {
  const items = PRESET_ITEMS[preset]();
  const itemsXml = items.map(renderItem).join('\n');

  return `<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by the Kiqr CLI. -->
<!-- Preset: ${preset}. Import it with: kiqr wp import kiqr-seed-${preset}.xml --authors=create -->
<rss version="2.0"
\txmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
\txmlns:content="http://purl.org/rss/1.0/modules/content/"
\txmlns:wfw="http://wellformedweb.org/CommentAPI/"
\txmlns:dc="http://purl.org/dc/elements/1.1/"
\txmlns:wp="http://wordpress.org/export/1.2/"
>
\t<channel>
\t\t<title>${escapeHtml(SITE_TITLE)}</title>
\t\t<link>${SITE_LINK}</link>
\t\t<description>${escapeHtml(SITE_DESCRIPTION)}</description>
\t\t<pubDate>${pubDate('2024-01-01T00:00:00')}</pubDate>
\t\t<language>en-US</language>
\t\t<wp:wxr_version>1.2</wp:wxr_version>
\t\t<wp:base_site_url>${SITE_LINK}</wp:base_site_url>
\t\t<wp:base_blog_url>${SITE_LINK}</wp:base_blog_url>
\t\t<wp:author>
\t\t\t<wp:author_id>1</wp:author_id>
\t\t\t<wp:author_login>${cdata(AUTHOR_LOGIN)}</wp:author_login>
\t\t\t<wp:author_email>${cdata(AUTHOR_EMAIL)}</wp:author_email>
\t\t\t<wp:author_display_name>${cdata(AUTHOR_NAME)}</wp:author_display_name>
\t\t\t<wp:author_first_name>${cdata('')}</wp:author_first_name>
\t\t\t<wp:author_last_name>${cdata('')}</wp:author_last_name>
\t\t</wp:author>
\t\t<generator>https://github.com/kiqr/cli</generator>
${itemsXml}
\t</channel>
</rss>
`;
}
